"""Additions merged into CPP_Design_Patterns_Field_Reference.html by apply.py.

Per pattern: definition (participants + consequences), two more real-world
examples (added to the existing three), a modern C++ alternative, and three
interview questions. Text supports `code` and **bold**; HTML allowed.
"""

def P(participants, consequences, examples, modern, qa):
    return {"participants": participants, "consequences": consequences,
            "moreExamples": [{"title": t, "body": b} for t, b in examples],
            "modern": modern, "qa": [{"q": q, "a": a} for q, a in qa]}

EXTRAS = {

"singleton": P(
 ["<b>Singleton</b>: the class that owns its single instance and exposes <code>instance()</code>",
  "<b>Client</b>: any code that reaches the instance through the global access point"],
 ["Controlled access to exactly one instance, created lazily and thread-safely (Meyers singleton, C++11 magic statics)",
  "Acts as hidden global state: dependencies become invisible and unit tests share state",
  "Destruction order across translation units is hard to control (static deinitialization order)"],
 [("Embedded HAL: one clock-tree / GPIO controller object", "Firmware code models a single physical peripheral block (clock controller, interrupt controller) as one object so no driver can accidentally create a second, conflicting view of the registers."),
  ("NVMe / storage test tools: one admin-queue owner", "A test harness keeps one object that owns the controller's admin queue so concurrent test threads serialize admin commands through it instead of racing on the doorbell.")],
 "Prefer <b>dependency injection</b>: create the object once in <code>main()</code> and pass a reference down. If a global is truly needed, a function-local <code>static</code> (Meyers singleton) is thread-safe since C++11; avoid double-checked locking by hand.",
 [("Is the Meyers singleton thread-safe?", "Yes since C++11: initialization of a function-local static is guaranteed to happen exactly once even with concurrent callers (the compiler inserts a guard). Before C++11 it was not guaranteed."),
  ("Why is Singleton often called an anti-pattern?", "It is global mutable state in disguise: hidden dependencies, order-dependent tests, and hard-to-swap implementations. Most uses are better served by passing one instance explicitly."),
  ("How do you make a singleton testable?", "Hide it behind an interface, and have code depend on the interface (injected), with the singleton only used at the composition root; tests inject a fake.")]),

"factory-method": P(
 ["<b>Product</b>: the interface of objects created (<code>Document</code>)",
  "<b>ConcreteProduct</b>: implementations (<code>PDFDocument</code>)",
  "<b>Creator</b>: declares the virtual factory method and uses it in its own logic",
  "<b>ConcreteCreator</b>: overrides the factory method to return a specific product"],
 ["Client code depends only on the Product interface, not concrete classes",
  "Adding a product means adding a creator subclass (parallel hierarchies can grow)",
  "Return <code>std::unique_ptr</code> so ownership is explicit and there are no leaks"],
 [("LLVM / compilers: target-specific objects", "Each target backend (x86, ARM, RISC-V) supplies factory methods that create its own instruction printer, register info and assembler objects while generic code drives them through base interfaces."),
  ("Test frameworks creating device drivers", "A base <code>TestFixture</code> calls <code>createDriver()</code>; the NVMe fixture returns an NVMe driver and the SATA fixture an AHCI driver, while setup and teardown logic stay in the base class.")],
 "A plain function or a registry (<code>std::unordered_map&lt;std::string, std::function&lt;std::unique_ptr&lt;Base&gt;()&gt;&gt;</code>) is often simpler than a creator hierarchy. With templates, <code>template&lt;class T&gt; std::unique_ptr&lt;Base&gt; make() { return std::make_unique&lt;T&gt;(); }</code> removes boilerplate.",
 [("Factory Method vs Abstract Factory?", "Factory Method creates <b>one</b> product via an overridable method (inheritance). Abstract Factory is an object that creates a <b>family</b> of related products (composition)."),
  ("Why return `std::unique_ptr` from factories?", "It makes ownership transfer explicit, prevents leaks on exceptions, and converts implicitly to <code>std::shared_ptr</code> if the caller needs shared ownership."),
  ("How do you avoid a giant switch statement in a factory?", "Use a registry map from key to creator function, where each type registers itself (for example via a static registration object), so adding a type doesn't touch the factory.")]),

"abstract-factory": P(
 ["<b>AbstractFactory</b>: interface with one create method per product (<code>createButton</code>, <code>createCheckbox</code>)",
  "<b>ConcreteFactory</b>: creates one consistent family (<code>DarkThemeFactory</code>)",
  "<b>AbstractProduct / ConcreteProduct</b>: product interfaces and their family-specific implementations",
  "<b>Client</b>: uses only the abstract interfaces"],
 ["Guarantees products from one family are used together",
  "Switching the whole family is one line (pass a different factory)",
  "Adding a new product type forces changes to every factory"],
 [("Cross-platform storage test rigs", "A <code>RealRigFactory</code> creates a power relay, a PCIe switch controller and a thermal chamber client; a <code>SimRigFactory</code> creates simulated versions of all three for CI, so test code is identical."),
  ("Graphics APIs abstraction (Vulkan / DirectX / Metal)", "Game engines define a render-device factory per API that creates matching buffers, textures and pipelines; mixing a Vulkan buffer with a DirectX pipeline is impossible by construction.")],
 "Templates can give a compile-time family: <code>template&lt;class Family&gt; void buildUI() { typename Family::Button b; }</code> (static polymorphism, no virtual calls) when the family is known at compile time.",
 [("When is Abstract Factory the right choice?", "When products come in families that must be consistent (real vs simulated hardware, UI themes, API backends) and you want to switch the whole family in one place."),
  ("What is its main weakness?", "Adding a new kind of product changes the abstract interface and every concrete factory; adding a new family is easy."),
  ("How does it help testing embedded code?", "Tests inject a factory that produces mock peripherals, so firmware logic runs on a host PC without hardware.")]),

"builder": P(
 ["<b>Builder</b>: provides step methods (<code>url()</code>, <code>header()</code>) and <code>build()</code>",
  "<b>Product</b>: the complex object being constructed",
  "<b>Director</b> (optional): encodes a standard construction sequence"],
 ["Readable construction of objects with many optional parts",
  "Validation can happen once in <code>build()</code>, so the product can be immutable",
  "Extra class to maintain; overkill for simple objects"],
 [("Protocol Buffers generated C++ code", "Generated message classes expose setters and nested mutable accessors used step by step to build a message before serialization, a builder-style construction API."),
  ("NVMe command construction in test tools", "A <code>CommandBuilder().opcode(0x02).nsid(1).slba(lba).nlb(7).build()</code> assembles a 64-byte submission queue entry, filling reserved fields and validating ranges once instead of in every test.")],
 "C++20 <b>designated initializers</b> (<code>Request r{.url = \"...\", .method = \"POST\"};</code>) cover simple aggregates without a builder. For fluent builders, return <code>*this</code> by reference and consider making <code>build()</code> <code>&amp;&amp;</code>-qualified to prevent reuse.",
 [("Builder vs telescoping constructors?", "Telescoping constructors (many overloads with growing parameter lists) are hard to read and error-prone with same-typed arguments; a builder names each step."),
  ("What does returning `*this` enable?", "Method chaining (a fluent interface): <code>b.url(x).method(y).build()</code>."),
  ("Where do you validate in a builder?", "In <code>build()</code>: check required fields and cross-field rules once, then produce a complete, preferably immutable object.")]),

"prototype": P(
 ["<b>Prototype</b>: interface declaring <code>clone()</code>",
  "<b>ConcretePrototype</b>: implements <code>clone()</code> by copying itself (often via the copy constructor)",
  "<b>Client</b>: creates objects by cloning a configured prototype"],
 ["Copy objects without knowing their concrete type (virtual constructor idiom)",
  "Cheap creation when setup is expensive",
  "Deep vs shallow copy must be decided carefully for pointer members"],
 [("Game engines: spawning from templates", "A configured enemy prototype (mesh handle, stats, AI state) is cloned for each spawn, far cheaper than loading and configuring from scratch."),
  ("Test pattern templates", "A storage test keeps a configured 4 KiB data-pattern buffer object and clones it per I/O, then stamps the LBA into each clone, avoiding regenerating the whole pattern.")],
 "Implement <code>clone()</code> with the copy constructor and return <code>std::unique_ptr&lt;Base&gt;</code>. A CRTP helper (<code>template&lt;class D&gt; struct Cloneable : Base { std::unique_ptr&lt;Base&gt; clone() const override { return std::make_unique&lt;D&gt;(static_cast&lt;const D&amp;&gt;(*this)); } };</code>) removes the boilerplate from every class.",
 [("Why can't you just use the copy constructor?", "The copy constructor needs the static type; through a <code>Base*</code> you don't know the concrete type. A virtual <code>clone()</code> dispatches to the right one."),
  ("Shallow vs deep copy in `clone()`?", "Raw owning pointers must be deep-copied or both clones free the same memory; with <code>unique_ptr</code> members the compiler forces you to decide."),
  ("What is covariant return type and does it work with smart pointers?", "Covariant returns let an override return <code>Derived*</code> instead of <code>Base*</code>, but they don't work with <code>std::unique_ptr</code>; return <code>unique_ptr&lt;Base&gt;</code>.")]),

"adapter": P(
 ["<b>Target</b>: the interface the client expects",
  "<b>Adaptee</b>: existing class with an incompatible interface",
  "<b>Adapter</b>: implements Target and translates calls to the Adaptee (by composition or private inheritance)"],
 ["Reuse existing or third-party code without modifying it",
  "Object adapters (composition) are more flexible than class adapters (inheritance)",
  "Adds an indirection layer; keep adapters thin (translation only)"],
 [("Wrapping vendor SDKs", "A vendor's C API for a PCIe analyzer (<code>vnd_capture_start(handle, flags)</code>) is wrapped by an adapter implementing your <code>ITraceCapture</code> interface, so switching vendors touches one class."),
  ("STL iterator adapters", "<code>std::back_inserter</code>, <code>std::reverse_iterator</code> and <code>std::stack</code>/<code>std::queue</code> (container adapters over <code>std::deque</code>) are adapters in the standard library itself.")],
 "For simple one-off adaptations, a lambda or <code>std::function</code> often suffices: <code>std::function&lt;double()&gt; readC = [&amp;]{ return (legacy.readF() - 32) * 5 / 9; };</code>.",
 [("Object adapter vs class adapter?", "Object adapter holds the adaptee (composition) and can adapt any subclass instance; class adapter inherits from the adaptee (often privately) and can override its behaviour but is tied to one class."),
  ("Adapter vs Facade vs Decorator?", "Adapter changes an interface to match another; Facade simplifies a subsystem with a new interface; Decorator keeps the same interface and adds behaviour."),
  ("Name adapters in the C++ standard library.", "<code>std::stack</code>, <code>std::queue</code>, <code>std::priority_queue</code> (container adapters), and iterator adapters like <code>std::reverse_iterator</code> and <code>std::back_insert_iterator</code>.")]),

"bridge": P(
 ["<b>Abstraction</b>: high-level interface holding a pointer to an Implementor",
  "<b>RefinedAbstraction</b>: variants of the abstraction",
  "<b>Implementor</b>: low-level interface (platform, device, renderer)",
  "<b>ConcreteImplementor</b>: platform-specific implementations"],
 ["Abstraction and implementation vary independently (M + N classes instead of M x N)",
  "Implementation can be switched at runtime",
  "The <b>pImpl idiom</b> is a special case that also hides implementation details and cuts compile times"],
 [("pImpl in large C++ libraries", "Qt uses d-pointers (a form of pImpl/Bridge) so the public class layout stays binary-compatible while private implementation changes between releases."),
  ("Logging frameworks", "Loggers (what and at which level) are separate from sinks (console, file, syslog, ring buffer in firmware), so any logger works with any sink.")],
 "The <b>pImpl</b> idiom: <code>class Widget { struct Impl; std::unique_ptr&lt;Impl&gt; p_; public: ~Widget(); };</code> with the destructor defined in the .cpp where <code>Impl</code> is complete.",
 [("What is the pImpl idiom and why use it?", "A class holds a pointer to a private implementation struct defined only in the .cpp: it hides details, keeps ABI stable, and reduces rebuilds when implementation changes."),
  ("Why must the destructor of a pImpl class be defined in the .cpp?", "<code>unique_ptr&lt;Impl&gt;</code>'s deleter needs the complete type; if the destructor is implicitly defined in the header, <code>Impl</code> is incomplete there and compilation fails."),
  ("Bridge vs Strategy?", "Both use composition; Strategy swaps one algorithm, Bridge separates two whole hierarchies that both keep growing.")]),

"composite": P(
 ["<b>Component</b>: common interface for leaves and containers (<code>FileSystemNode</code>)",
  "<b>Leaf</b>: element with no children (<code>File</code>)",
  "<b>Composite</b>: element holding children and forwarding operations to them (<code>Directory</code>)"],
 ["Clients treat single objects and groups uniformly",
  "Recursive operations (size, render, run) are written once",
  "Harder to restrict which child types are allowed; deep trees risk stack depth in recursion"],
 [("Scene graphs in game engines", "Nodes contain meshes, lights and other nodes; transforms and rendering propagate recursively down the tree."),
  ("Test suites and command sequences", "A test suite contains test cases and nested suites, all with <code>run()</code>; a firmware update sequence can be a composite of steps and sub-sequences.")],
 "Watch the default-argument trap shown in this example: default arguments are bound to the <b>static</b> type. The base declared <code>print(int indent = 0)</code> but the overrides don't, so <code>root-&gt;print()</code> on a <code>unique_ptr&lt;Directory&gt;</code> doesn't compile; call <code>print(0)</code> or avoid defaults on virtual functions (or use a non-virtual public wrapper).",
 [("How do you implement Composite with smart pointers?", "Children as <code>std::vector&lt;std::unique_ptr&lt;Component&gt;&gt;</code>, giving clear ownership and automatic cleanup of the whole tree."),
  ("Why are default arguments on virtual functions dangerous?", "The default comes from the static type of the expression, while the function body comes from the dynamic type, so the same call can use different defaults depending on the pointer type."),
  ("Which pattern adds new operations over a Composite tree?", "Visitor (or <code>std::visit</code> over a variant-based tree), so operations like export or validation don't require editing each node class.")]),

"decorator": P(
 ["<b>Component</b>: the interface (<code>DataStream</code>)",
  "<b>ConcreteComponent</b>: the base object (<code>FileStream</code>)",
  "<b>Decorator</b>: holds a Component and implements the same interface, adding behaviour before/after delegating"],
 ["Add responsibilities at runtime and combine them freely",
  "Avoids a subclass for every combination",
  "Many small wrapper objects; order of wrapping matters"],
 [("I/O stacks", "Compression, encryption and buffering layers wrapped around a raw file or socket stream, each with the same read/write interface (as in Boost.Iostreams filters)."),
  ("Instrumenting device drivers in tests", "A <code>TracingDevice</code> decorator wraps a real <code>BlockDevice</code> and logs every command with latency, while a <code>FaultInjectingDevice</code> decorator corrupts selected reads for negative testing.")],
 "For functions, higher-order wrappers with lambdas: <code>auto timed = [f](auto&amp;&amp;... a){ auto t0 = std::chrono::steady_clock::now(); auto r = f(std::forward&lt;decltype(a)&gt;(a)...); /* log */ return r; };</code>",
 [("Decorator vs inheritance?", "Inheritance fixes behaviour at compile time and multiplies subclasses for combinations; decorators compose behaviour at runtime."),
  ("Decorator vs Proxy?", "Both wrap with the same interface; decorators add behaviour and are stacked by the client, proxies control access (lazy loading, remote, permissions)."),
  ("What is a common bug when writing decorators?", "Forgetting to forward some interface methods (or making them non-virtual), so calls bypass the decorator or hit an unimplemented function.")]),

"facade": P(
 ["<b>Facade</b>: simple interface for common tasks",
  "<b>Subsystem classes</b>: do the real work; unaware of the facade",
  "<b>Client</b>: uses the facade (and may still use subsystems directly)"],
 ["Simplifies use and reduces coupling to subsystem details",
  "Can become a god object if it accumulates everything",
  "Does not prevent direct access for advanced users"],
 [("SDK entry points", "Libraries like libcurl's \"easy\" interface wrap a complex multi-handle subsystem behind a small set of calls for the common case."),
  ("Device bring-up sequence", "A <code>DeviceSession::open()</code> facade powers the device, waits for link-up, enables the controller, creates I/O queues and reads identify data, replacing 40 lines of setup in every test.")],
 "Namespaces with free functions often make a lighter facade than a class: <code>namespace nvme::easy { Result writeVerify(Device&amp;, Lba, std::span&lt;const std::byte&gt;); }</code>.",
 [("Facade vs Adapter?", "Facade defines a new simplified interface over many objects; Adapter makes one existing interface match another expected interface."),
  ("How do you stop a facade becoming a god object?", "Split it by use case (bring-up, I/O, diagnostics), keep business logic in subsystems, and keep the facade as orchestration only."),
  ("Give a facade from your experience.", "Describe a real subsystem and what the facade hid: ordering constraints, error handling, and cleanup, plus how it simplified callers.")]),

"flyweight": P(
 ["<b>Flyweight</b>: shared object holding intrinsic (context-independent) state",
  "<b>FlyweightFactory</b>: creates and caches flyweights, returning shared instances",
  "<b>Client</b>: stores extrinsic state (position, size) and passes it when needed"],
 ["Large memory savings when many objects share state",
  "Intrinsic state must be immutable, or all users see changes",
  "Extra complexity: separating intrinsic and extrinsic state"],
 [("Text rendering glyph caches", "One glyph bitmap per (font, size, character) shared by every occurrence on the page; each occurrence stores only its position."),
  ("String interning in compilers", "Compilers intern identifiers (e.g. LLVM's string pools) so each distinct name is stored once and compared by pointer.")],
 "Share immutable state with <code>std::shared_ptr&lt;const T&gt;</code> from a factory cache (<code>std::unordered_map&lt;Key, std::weak_ptr&lt;const T&gt;&gt;</code> lets unused flyweights be freed), or store small integer IDs into a table.",
 [("Intrinsic vs extrinsic state?", "Intrinsic state is shared and context-independent (glyph shape); extrinsic state depends on context and is supplied by the client (glyph position)."),
  ("Why store `weak_ptr` in the flyweight cache?", "So flyweights nobody uses anymore can be destroyed; the cache doesn't keep them alive forever."),
  ("How is Flyweight different from Singleton?", "Singleton has one instance of a class; Flyweight has one instance <b>per distinct intrinsic state</b>, possibly many in total.")]),

"proxy": P(
 ["<b>Subject</b>: common interface",
  "<b>RealSubject</b>: the real object",
  "<b>Proxy</b>: implements Subject, controls access to RealSubject (lazy creation, permission checks, remote calls, caching)"],
 ["Adds control without changing the real object",
  "Can hide latency (remote proxy) that callers should be aware of",
  "Smart pointers are proxies for memory ownership"],
 [("Smart pointers", "<code>std::shared_ptr</code> and <code>std::unique_ptr</code> act as proxies around raw pointers, adding ownership and lifetime management behind <code>operator-&gt;</code> and <code>operator*</code>."),
  ("Remote device access in labs", "A <code>RemoteDeviceProxy</code> implements the <code>BlockDevice</code> interface but forwards commands over gRPC to a lab host, so tests run the same code against a local or remote drive.")],
 "Overload <code>operator-&gt;</code> for transparent proxies: it is applied repeatedly (drill-down) until a raw pointer is returned, which is how smart pointers and lock-guarding proxies work.",
 [("Types of proxy?", "Virtual (lazy creation), protection (access checks), remote (another process/machine), caching/logging, and smart reference (reference counting)."),
  ("How is `std::shared_ptr` a proxy?", "It controls access to the managed object via <code>operator-&gt;</code> and manages its lifetime with a reference-counted control block."),
  ("Proxy vs Decorator?", "Same structure; intent differs: proxy controls access and often manages the real object's lifecycle, decorator adds responsibilities.")]),

"chain-of-responsibility": P(
 ["<b>Handler</b>: interface for handling a request and holding the next handler",
  "<b>ConcreteHandler</b>: handles what it can, otherwise forwards",
  "<b>Client</b>: sends the request to the first handler"],
 ["Decouples sender from receiver; handlers can be reordered or added",
  "No guarantee a request is handled unless a default handler exists",
  "Debugging can be harder: which handler acted?"],
 [("Interrupt / event dispatch in firmware", "A chain of handlers checks an error event: the retry handler, then the error-recovery handler, then the logger, then a fatal handler that asserts."),
  ("HTTP middleware (e.g. in C++ web frameworks)", "Authentication, rate limiting and compression handlers wrap the request pipeline; each can respond early or pass the request on.")],
 "A <code>std::vector&lt;std::function&lt;bool(Request&amp;)&gt;&gt;</code> iterated until one returns true is often simpler than linked handler objects.",
 [("When does Chain of Responsibility fit?", "When several independent handlers may process a request, the set or order should be configurable, and a handler may stop further processing."),
  ("What happens if no handler handles the request?", "It must be defined: a default terminal handler, an error, or explicit ignore; leaving it undefined is a bug."),
  ("Real example in exception handling?", "C++ exceptions propagate up the call stack through catch handlers until one matches: a language-level chain of responsibility.")]),

"command": P(
 ["<b>Command</b>: interface with <code>execute()</code> (and often <code>undo()</code>)",
  "<b>ConcreteCommand</b>: binds a receiver and parameters",
  "<b>Invoker</b>: triggers commands, may queue or log them",
  "<b>Receiver</b>: the object that does the actual work"],
 ["Requests become objects: queue, log, retry, undo, send across threads",
  "Undo requires storing enough state to reverse",
  "Many small classes, unless you use callables"],
 [("Thread pools and task queues", "Work items submitted to a thread pool are commands (<code>std::function&lt;void()&gt;</code> or <code>std::packaged_task</code>) executed later by worker threads."),
  ("NVMe submission queues", "Each 64-byte submission queue entry is literally a command object: opcode plus parameters, queued by the host and executed later by the controller, with the completion reported separately.")],
 "Use <code>std::function&lt;void()&gt;</code> or lambdas capturing their arguments for simple commands; <code>std::packaged_task</code> when a result must be returned through a <code>std::future</code>.",
 [("How do you implement undo/redo?", "Commands with <code>execute()</code> and <code>undo()</code>, an undo stack and a redo stack; executing a new command clears the redo stack."),
  ("Command vs Strategy?", "Command encapsulates a request (what to do and on what), often executed later; Strategy encapsulates an interchangeable algorithm used by a context now."),
  ("Why is `std::function` a command?", "It stores any callable with bound state behind a uniform <code>operator()</code>, so invokers can store, queue and execute it without knowing the concrete type.")]),

"interpreter": P(
 ["<b>AbstractExpression</b>: interface with <code>interpret(context)</code>",
  "<b>TerminalExpression</b>: literals and variables",
  "<b>NonterminalExpression</b>: operators combining sub-expressions",
  "<b>Context</b>: variable values and global information"],
 ["Easy to extend a small grammar with new expression classes",
  "Complex grammars become unmanageable: use a parser generator",
  "Evaluation by tree walking is slower than compiled code"],
 [("Test-script DSLs", "Validation teams define mini-languages for test sequences (<code>write lba=0 len=8; verify; power_cycle</code>) interpreted by the framework, so non-programmers can compose tests."),
  ("Expression evaluators and filters", "Packet filters (BPF-like), log query languages and spreadsheet formulas are parsed into trees and evaluated with interpreter-style nodes.")],
 "Represent the AST with <code>std::variant</code> of node types and evaluate with <code>std::visit</code>, avoiding a class hierarchy and virtual calls.",
 [("When is the Interpreter pattern appropriate?", "For small, stable languages (rules, filters, simple scripts) where readability and extensibility matter more than raw speed."),
  ("How does Interpreter relate to Composite?", "The expression tree is a Composite: nonterminal nodes contain child expressions."),
  ("What do you use for a bigger language?", "A parser generator or hand-written recursive-descent parser producing an AST, then a separate evaluator or compiler (Visitor), rather than growing interpreter classes.")]),

"iterator": P(
 ["<b>Iterator</b>: provides sequential access (increment, dereference, compare)",
  "<b>Aggregate</b>: the collection, providing <code>begin()</code>/<code>end()</code>",
  "<b>Client</b>: traverses without knowing the internal structure"],
 ["Uniform traversal across containers and algorithms",
  "Iterator invalidation rules must be respected (e.g. <code>vector</code> reallocation)",
  "Enables the whole STL algorithm library"],
 [("The STL", "Every STL container exposes iterators, and algorithms like <code>std::sort</code> and <code>std::find</code> work on iterator ranges, not containers: the most famous Iterator implementation."),
  ("Paging through device logs", "An iterator over an NVMe telemetry or error log fetches the next page with a Get Log Page command only when the loop reaches it, hiding offsets and page sizes.")],
 "C++20 <b>ranges</b> and views (<code>std::views::filter</code>, <code>std::views::transform</code>) compose lazy iteration; <code>std::generator</code> (C++23) lets a coroutine produce values like a Python generator.",
 [("What is iterator invalidation?", "Operations that change a container's storage can make existing iterators dangling, e.g. <code>push_back</code> on a <code>vector</code> that reallocates, or <code>erase</code> on the erased element."),
  ("What do you need to make a class usable in a range-for loop?", "<code>begin()</code> and <code>end()</code> (member or free) returning iterators that support <code>!=</code>, prefix <code>++</code> and unary <code>*</code>."),
  ("What are iterator categories?", "Input, output, forward, bidirectional, random access and (C++20) contiguous; algorithms require minimum categories (e.g. <code>std::sort</code> needs random access).")]),

"mediator": P(
 ["<b>Mediator</b>: interface for communication between colleagues",
  "<b>ConcreteMediator</b>: coordinates colleagues and holds the interaction logic",
  "<b>Colleague</b>: components that talk only to the mediator"],
 ["Reduces many-to-many dependencies to one-to-many",
  "Colleagues become reusable",
  "The mediator can grow into a complex god object"],
 [("GUI dialogs (Qt)", "A dialog class wires widget signals to slots and decides how widgets affect each other, so widgets stay independent and reusable."),
  ("Test orchestrators", "Device workers, the power controller and the results collector don't call each other; an orchestrator mediates: when a test finishes, it tells the collector, then asks the power controller to cycle the device.")],
 "Signal/slot libraries (Qt, Boost.Signals2) or a small event bus provide the plumbing; keep the coordination rules in one mediator class.",
 [("Mediator vs Observer?", "Observer broadcasts changes to subscribers without deciding what they do; Mediator actively coordinates a group and encapsulates their interaction rules."),
  ("Mediator vs Facade?", "Facade simplifies access to a subsystem for outside clients; Mediator coordinates peers that know and talk to it."),
  ("Main risk of Mediator?", "Centralizing so much logic that the mediator becomes a hard-to-test god object; split by use case.")]),

"memento": P(
 ["<b>Originator</b>: creates a memento of its state and restores from it",
  "<b>Memento</b>: opaque snapshot of the originator's state",
  "<b>Caretaker</b>: stores mementos without inspecting them"],
 ["Undo/rollback without exposing internals",
  "Snapshots can be memory-expensive for large state",
  "Encapsulation can be enforced with a private nested class plus <code>friend</code>"],
 [("Editors and CAD tools", "Undo history stores snapshots (or diffs) of document state before each edit."),
  ("Firmware configuration rollback", "Before applying a new feature configuration to a drive, the test saves the current settings snapshot and restores it in teardown so later tests start from defaults.")],
 "Make the memento a nested class with a private constructor and declare the originator a <code>friend</code>, so only the originator can read it; for large states store diffs or use copy-on-write.",
 [("Memento vs Command for undo?", "Memento stores state snapshots (simple, memory-heavy); Command stores the operation and its inverse (light, but every command needs correct undo)."),
  ("How does C++ enforce memento encapsulation?", "Private nested memento type with the originator as <code>friend</code>, exposing no public accessors to the caretaker."),
  ("How do you limit memory for long undo histories?", "Cap the history length, store diffs instead of full snapshots, or share unchanged data with copy-on-write.")]),

"observer": P(
 ["<b>Subject</b>: keeps a list of observers and notifies them",
  "<b>Observer</b>: interface with <code>update()</code> / callback",
  "<b>ConcreteObserver</b>: reacts to notifications"],
 ["Loose coupling between event source and reactions",
  "Lifetime issues: dangling observers if not unsubscribed",
  "Notification order is usually unspecified"],
 [("GUI frameworks", "Qt signals/slots and model/view updates notify views when the model changes."),
  ("Hardware event monitoring", "A temperature monitor subject notifies a throttling policy, a logger and a test-abort guard when the drive crosses a thermal threshold.")],
 "Store <code>std::weak_ptr</code> to observers (skip expired ones) or return an RAII subscription handle that unsubscribes in its destructor; Boost.Signals2 provides thread-safe signals with scoped connections.",
 [("How do you avoid dangling observers?", "RAII subscription tokens that unsubscribe on destruction, or storing <code>weak_ptr</code> and pruning expired entries."),
  ("Observer vs Pub/Sub?", "Observer registers directly with the subject; pub/sub uses a broker so publishers and subscribers don't know each other and delivery can be asynchronous."),
  ("Thread-safety concerns?", "Notifying while another thread subscribes or unsubscribes; copy the observer list under a lock and notify outside the lock to avoid deadlocks.")]),

"state": P(
 ["<b>Context</b>: holds the current state and delegates behaviour to it",
  "<b>State</b>: interface for state-specific behaviour",
  "<b>ConcreteState</b>: implements behaviour and decides transitions"],
 ["Removes large switch statements on a state variable",
  "Transitions are explicit and localized",
  "More classes; a table-driven FSM may be simpler for small machines"],
 [("Protocol stacks", "TCP connection handling (LISTEN, SYN_RCVD, ESTABLISHED, ...) is the textbook State example; each state accepts different events."),
  ("Device power and link states", "An NVMe or PCIe device model in a test framework moves through power states (PS0 to PS4) or link states (L0, L1, L2), with commands allowed or rejected per state.")],
 "Use <code>std::variant&lt;Idle, Running, Error&gt;</code> for states and <code>std::visit</code> for transitions: states are values, invalid transitions can be compile-time errors, and there's no heap allocation.",
 [("State vs Strategy?", "Same structure; Strategy is chosen by the client and rarely changes, State objects change themselves as the context moves through its lifecycle."),
  ("When is a switch statement fine?", "Few states and simple behaviour; switch to State (or a variant FSM) when the same switch repeats across many methods."),
  ("How do you model a finite state machine without inheritance?", "A transition table (<code>std::map&lt;std::pair&lt;State, Event&gt;, State&gt;</code>) or <code>std::variant</code> states with <code>std::visit</code>.")]),

"strategy": P(
 ["<b>Strategy</b>: interface for an algorithm",
  "<b>ConcreteStrategy</b>: interchangeable implementations",
  "<b>Context</b>: uses a strategy and can switch it"],
 ["Algorithms swap at runtime without changing the context",
  "Clients must know which strategy to choose",
  "Callables (<code>std::function</code>, lambdas, templates) often replace class hierarchies"],
 [("STL algorithms with comparators and hashers", "<code>std::sort(v.begin(), v.end(), cmp)</code>, <code>std::unordered_map&lt;K, V, Hash&gt;</code> and allocators are compile-time strategies."),
  ("I/O workload generators", "A workload engine takes an access-pattern strategy (sequential, random, zipfian, hot-spot) to generate LBAs, so the same engine drives every test profile.")],
 "Compile-time strategy via templates (policy-based design): <code>template&lt;class Compare&gt; class Sorter { Compare cmp_; };</code> gives zero overhead; runtime strategy via <code>std::function</code> when choice happens at runtime.",
 [("Runtime vs compile-time strategies in C++?", "Runtime: virtual interface or <code>std::function</code>, chosen dynamically. Compile-time: template parameters (policies), inlined with no overhead but fixed at compile time."),
  ("What is policy-based design?", "Composing class behaviour from template parameters (policies) such as allocation, threading or checking, as popularized by Alexandrescu's Modern C++ Design."),
  ("Strategy vs Template Method?", "Strategy uses composition to swap a whole algorithm; Template Method uses inheritance to vary steps of a fixed algorithm.")]),

"template-method": P(
 ["<b>AbstractClass</b>: defines the template method (fixed algorithm) and primitive operations",
  "<b>ConcreteClass</b>: implements the primitive operations / hooks"],
 ["Enforces an invariant sequence while allowing customization",
  "Inheritance couples subclasses to the base",
  "The <b>Non-Virtual Interface (NVI)</b> idiom is the C++ form: public non-virtual method, private virtual hooks"],
 [("Test fixtures", "Google Test's <code>SetUp()</code>/<code>TearDown()</code> hooks are called by the framework around each test body."),
  ("Firmware update flows", "A base <code>FirmwareUpdater::run()</code> fixes download, verify, commit and reset steps; vendor subclasses override only the transport or activation step.")],
 "Use the <b>NVI idiom</b>: <code>public: void process() { read(); transform(); write(); } private: virtual void transform() = 0;</code>, so derived classes customize steps but can't change the order. CRTP gives a compile-time version without virtual calls.",
 [("What is the Non-Virtual Interface idiom?", "Public functions are non-virtual and call private (or protected) virtual hooks, letting the base enforce pre/post-conditions and ordering."),
  ("Template Method vs Strategy?", "Template Method varies steps via inheritance with a fixed skeleton; Strategy swaps the whole algorithm via composition."),
  ("How can CRTP implement Template Method?", "The base template calls <code>static_cast&lt;Derived*&gt;(this)-&gt;step()</code>, resolving steps at compile time without virtual dispatch.")]),

"visitor": P(
 ["<b>Visitor</b>: interface with a <code>visit()</code> overload per element type",
  "<b>ConcreteVisitor</b>: one operation across all element types",
  "<b>Element</b>: interface with <code>accept(Visitor&amp;)</code>",
  "<b>ConcreteElement</b>: calls <code>visitor.visit(*this)</code> (double dispatch)"],
 ["Adding operations is easy (new visitor)",
  "Adding element types is hard (every visitor changes)",
  "Can break encapsulation if visitors need internals"],
 [("Clang AST tools", "Clang's <code>RecursiveASTVisitor</code> lets tools implement <code>VisitCallExpr</code>, <code>VisitFunctionDecl</code> and so on, used by clang-tidy checks and refactoring tools."),
  ("Exporting test results", "Result nodes (suite, test case, step, measurement) are visited by a JUnit exporter, an HTML report exporter and a database writer without changing the node classes.")],
 "<code>std::variant&lt;Circle, Square&gt;</code> plus <code>std::visit</code> with an overloaded lambda set (<code>template&lt;class... Ts&gt; struct overloaded : Ts... { using Ts::operator()...; };</code>) gives visitor behaviour with value semantics and exhaustiveness checking by the compiler.",
 [("What is double dispatch?", "Choosing the function based on two runtime types: <code>element.accept(visitor)</code> dispatches on the element, then <code>visitor.visit(*this)</code> on the visitor via overload resolution."),
  ("When would you use `std::variant` + `std::visit` instead?", "When the set of types is closed and known; you get value semantics, no heap allocation, and a compile error if a visitor misses a type."),
  ("Main trade-off of Visitor?", "Easy to add operations, hard to add element types; choose it when types are stable and operations grow.")]),
}
